import "./globals.css";
import oth from "./oth.module.css"
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <h1 className={oth.clr}>common layout</h1>
        {children}
      </body>
    </html>
  );
}
